export type Circuit = {
  slug: string;
  name: string;
  officialName: string;
  country: string;
  city: string;
  region: "Europe" | "Americas" | "Middle East" | "Asia-Pacific";
  character: string;
  distance: string;
  lapDistanceKm: number;
  laps: number;
  totalDistanceKm: number;
  turns: string;
  turnCount: number;
  lapType: string;
  lapRecord: { time: string; driver: string; year: number };
  drsZones: number;
  overtakingDifficulty: "Low" | "Moderate" | "High" | "Extreme";
  downforceLevel: "Low" | "Medium" | "High" | "Maximum";
  tireStress: "Low" | "Medium" | "High" | "Very High" | "Extreme";
  gearShiftsPerLap: number;
  intro: string;
  sectors: { name: string; focus: string; description: string }[];
  lessons: { title: string; text: string }[];
  fieldNote: string;
  sourceUrl: string;
  officialUrl: string;
};

export const circuits: Circuit[] = [
  {
    slug: "zandvoort",
    name: "Zandvoort",
    officialName: "Circuit Zandvoort",
    country: "Netherlands",
    city: "Zandvoort",
    region: "Europe",
    character: "Rollercoaster in the coastal dunes with 19° steep banking",
    distance: "4.259 km",
    lapDistanceKm: 4.259,
    laps: 72,
    totalDistanceKm: 306.648,
    turns: "14 turns",
    turnCount: 14,
    lapType: "Short technical dunes circuit",
    lapRecord: { time: "1:11.097", driver: "Lewis Hamilton", year: 2021 },
    drsZones: 2,
    overtakingDifficulty: "High",
    downforceLevel: "Maximum",
    tireStress: "High",
    gearShiftsPerLap: 48,
    intro: "Flowing through the North Sea sand dunes, Zandvoort is one of the most distinctive circuits on the calendar. Featuring two uniquely banked corners (Hugenholtz at 19° and Arie Luyendyk at 18°), it demands immense aerodynamic commitment and rewards progressive throttle application.",
    sectors: [
      { name: "Sector 1 (Tarzan & Hugenholtz)", focus: "Tarzan hairpin & 19° banking", description: "Iconic Tarzanbocht into the steep banking of Hugenholtz where drivers ride high up the wall." },
      { name: "Sector 2 (Scheivlak to Arena)", focus: "High-speed blind drops", description: "Fearsome 250 km/h Scheivlak downhill crest into the dunes." },
      { name: "Sector 3 (Kumho & Luyendyk)", focus: "Banked DRS launch", description: "Banked Turn 14 with DRS open, launching cars towards the finish line." },
    ],
    lessons: [
      { title: "Riding the Hugenholtz banking", text: "Taking the higher line on the 19-degree banking shortens the time required to apply full throttle." },
      { title: "Windblown sand on track", text: "Coastal winds deposit fine beach sand on the asphalt, drastically lowering off-line grip." },
      { title: "Commitment over Scheivlak crest", text: "Any lift over the blind crest unsettles the diffuser and costs half a second." },
    ],
    fieldNote: "Zandvoort refuses to sit flat; banking and coastal winds make every lap dynamic.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/netherlands",
    officialUrl: "https://www.circuitzandvoort.nl/en/",
  },
  {
    slug: "monza",
    name: "Monza",
    officialName: "Autodromo Nazionale Monza",
    country: "Italy",
    city: "Monza",
    region: "Europe",
    character: "The Temple of Speed: skinny wings, 360 km/h and savage chicane curbs",
    distance: "5.793 km",
    lapDistanceKm: 5.793,
    laps: 53,
    totalDistanceKm: 306.720,
    turns: "11 turns",
    turnCount: 11,
    lapType: "Low-drag temple of speed",
    lapRecord: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Low",
    tireStress: "Medium",
    gearShiftsPerLap: 36,
    intro: "The spiritual heart of Italian motorsport. Monza is the fastest track in the world, with cars spending over 76% of the lap at full throttle. Teams run bespoke ultra-skinny rear wings, testing braking stability into brutal chicanes.",
    sectors: [
      { name: "Sector 1 (Variante del Rettifilo)", focus: "360 km/h to 70 km/h stop", description: "Massive braking into Turn 1 chicane, followed by the majestic flat-out Curva Grande." },
      { name: "Sector 2 (Variante della Roggia & Lesmos)", focus: "Roggia chicane & twin Lesmos", description: "Curb-bashing chicane into the technical mid-speed Lesmo 1 and Lesmo 2 right-handers." },
      { name: "Sector 3 (Ascari to Parabolica/Alboreto)", focus: "Ascari switchback & Parabolica", description: "The high-speed Ascari chicane leading onto the back straight and the majestic Curva Alboreto." },
    ],
    lessons: [
      { title: "Braking without aerodynamic downforce", text: "With tiny rear wings, cars are light and skittish under heavy braking from 360 km/h." },
      { title: "Attacking the Ascari curbs", text: "Taking maximum curb at Ascari entry straightens the chicane for higher exit speed." },
      { title: "Slipstream tow tactics in qualifying", text: "A clean tow down the main straight is worth up to 0.4s per lap in Q3." },
    ],
    fieldNote: "At Monza, low drag brings speed, but braking precision through the chicanes wins trophies.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/italy",
    officialUrl: "https://www.monzanet.it/en/",
  },
  {
    slug: "madrid",
    name: "Madrid",
    officialName: "MADRING (Circuito de Madrid)",
    country: "Spain",
    city: "Madrid",
    region: "Europe",
    character: "Brand-new hybrid street-permanent circuit with IFEMA banked curve",
    distance: "5.474 km",
    lapDistanceKm: 5.474,
    laps: 56,
    totalDistanceKm: 306.544,
    turns: "20 turns",
    turnCount: 20,
    lapType: "Hybrid street circuit",
    lapRecord: { time: "1:18.450", driver: "Inaugural Round", year: 2026 },
    drsZones: 3,
    overtakingDifficulty: "Moderate",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 58,
    intro: "Joining the World Championship calendar, MADRING combines permanent racing infrastructure around IFEMA Madrid with fast street sections and an ambitious banked curve, creating a high-energy urban battleground.",
    sectors: [
      { name: "Sector 1 (IFEMA Pavilion Arena)", focus: "Fast stadium complex", description: "Technical multi-apex corners weaving around the convention center pavilions." },
      { name: "Sector 2 (The Banked Curve)", focus: "Centrifugal load & tunnel pass", description: "High-speed sweeping banked turn transitioning under the railway bridge." },
      { name: "Sector 3 (Valdebebas straight)", focus: "Overtaking braking zone", description: "Long acceleration blast ending in a 90-degree left-hand stadium amphitheater." },
    ],
    lessons: [
      { title: "Adapting to mixed grip asphalt", text: "Transitioning from dedicated circuit asphalt to standard city street tarmac changes friction coefficients instantly." },
      { title: "Wall proximity in tunnel transition", text: "Lighting shifts and narrow barriers create high mental load during rapid acceleration." },
      { title: "Setup versatility", text: "Requires stiff suspension for aero stability, yet compliant enough for urban bumps." },
    ],
    fieldNote: "Madrid's MADRING brings street theater and high-speed banking to Spain's capital.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/spain-madrid",
    officialUrl: "https://www.ifema.es/en/madring",
  },
  {
    slug: "baku",
    name: "Baku",
    officialName: "Baku City Circuit",
    country: "Azerbaijan",
    city: "Baku",
    region: "Asia-Pacific",
    character: "2.2 km main straight, medieval castle chicane and 90° city corners",
    distance: "6.003 km",
    lapDistanceKm: 6.003,
    laps: 51,
    totalDistanceKm: 306.049,
    turns: "20 turns",
    turnCount: 20,
    lapType: "High-speed street circuit",
    lapRecord: { time: "1:43.009", driver: "Charles Leclerc", year: 2019 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Low",
    tireStress: "Medium",
    gearShiftsPerLap: 64,
    intro: "Baku is a circuit of extreme contradictions: a 2.2-kilometer flat-out blast along the Caspian promenade where cars hit 350 km/h, paired with the tightest section in Formula 1 around the ancient medieval Old City castle walls (Turn 8 is just 7.6m wide).",
    sectors: [
      { name: "Sector 1 (Turns 1–6)", focus: "90° boulevard braking zones", description: "Heavy braking from top speed into 90-degree corners with runaway escape roads." },
      { name: "Sector 2 (Turns 7–12)", focus: "The 7.6m Castle section", description: "Uphill squeeze past the 12th-century stone fortress requiring inch-perfect placement." },
      { name: "Sector 3 (Turns 13–20)", focus: "2.2 km flat-out waterfront blast", description: "Kinks taken flat out at 340+ km/h into the main straight slipstream wars." },
    ],
    lessons: [
      { title: "Surviving the Castle Section", text: "Entering Turn 8 even 5 km/h too fast means bouncing off the stone barrier into the opposite wall." },
      { title: "Brake temperature drop", text: "After the 25-second flat-out straight, front brake discs cool down drastically, making lock-ups into Turn 1 frequent." },
      { title: "Safety car restarts", text: "Baku produces more safety car chaos and lead changes than almost any other venue." },
    ],
    fieldNote: "In Baku, low downforce gives you 350 km/h on the seaside boulevard, but leaves you clinging to the walls in the Old Town.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/azerbaijan",
    officialUrl: "https://www.bakucitycircuit.com/",
  },
  {
    slug: "sepang",
    name: "Sepang",
    officialName: "Sepang International Circuit",
    country: "Malaysia",
    city: "Sepang",
    region: "Asia-Pacific",
    character: "Wide racing lines, dual back-to-back straights and tropical downpours",
    distance: "5.543 km",
    lapDistanceKm: 5.543,
    laps: 56,
    totalDistanceKm: 310.408,
    turns: "15 turns",
    turnCount: 15,
    lapType: "Permanent circuit",
    lapRecord: { time: "1:34.080", driver: "Sebastian Vettel", year: 2017 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "High",
    tireStress: "Very High",
    gearShiftsPerLap: 50,
    intro: "Sepang features wide flowing arcs, colossal sweeping turns, and back-to-back 1km straights separated by a sharp hairpin grandstand arena.",
    sectors: [
      { name: "Sector 1 (Turns 1–4)", focus: "Downhill switchback chicane", description: "Tight Turn 1-2 downhill chicane opening into the sweeping uphill right-hander at Turn 3." },
      { name: "Sector 2 (Turns 5–11)", focus: "High-speed aero sweeps", description: "Fast left-right sweepers at Turns 5 and 6 putting colossal lateral load through the tires." },
      { name: "Sector 3 (Turns 12–15)", focus: "Opposite straights & hairpin", description: "Back straight leading into the off-camber final Turn 15 hairpin and main straight." },
    ],
    lessons: [
      { title: "Monsoon strategy readiness", text: "Tropical afternoon downpours can flood the track in 90 seconds, demanding instant pit calls." },
      { title: "Multiple racing lines", text: "Sepang's 16-meter wide track allows cutbacks and switchbacks in almost every braking zone." },
      { title: "Tire blistering under thermal load", text: "High asphalt temperatures cook front tires in long sweeping Turns 5 and 6." },
    ],
    fieldNote: "Sepang tests both aerodynamic balance and driver physical endurance in tropical humidity.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/malaysia",
    officialUrl: "https://www.sepangcircuit.com/",
  },
  {
    slug: "marina-bay",
    name: "Marina Bay",
    officialName: "Marina Bay Street Circuit",
    country: "Singapore",
    city: "Singapore",
    region: "Asia-Pacific",
    character: "Night race torture chamber with 19 corners, tropical heat and safety car probability",
    distance: "4.940 km",
    lapDistanceKm: 4.940,
    laps: 62,
    totalDistanceKm: 306.143,
    turns: "19 turns",
    turnCount: 19,
    lapType: "Night street circuit",
    lapRecord: { time: "1:34.486", driver: "Daniel Ricciardo", year: 2024 },
    drsZones: 4,
    overtakingDifficulty: "High",
    downforceLevel: "Maximum",
    tireStress: "High",
    gearShiftsPerLap: 72,
    intro: "The toughest physical test in modern motorsport. Over 62 laps in 85% equatorial humidity under 1,600 floodlights, drivers lose up to 4kg of body weight through continuous cornering with zero room for error.",
    sectors: [
      { name: "Sector 1 (Sheares to Republic)", focus: "Turn 1-3 complex & boulevard", description: "Braking into Sheares corner from 300 km/h, followed by the flat-out blast down Republic Boulevard." },
      { name: "Sector 2 (Padang to Singapore Sling)", focus: "Turn 7 braking & Connaught", description: "Braking past the historic Fullerton Hotel and Padang grandstands." },
      { name: "Sector 3 (Bay Bypass Straight)", focus: "Turn 16 to the Bay finish", description: "Fast bypass straight eliminating the old grandstand underpass into the final sweeps." },
    ],
    lessons: [
      { title: "Managing cockpit heat exhaustion", text: "Cabin temps exceed 55°C; cognitive focus must remain pristine for two full hours." },
      { title: "100% Safety car probability", text: "Every Singapore GP has featured at least one safety car, demanding proactive pit strategies." },
      { title: "Traction over painted city lines", text: "White pedestrian crossing lines become slick as glass during full-power acceleration." },
    ],
    fieldNote: "Marina Bay is motorsport's ultimate endurance test under artificial daylight.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/singapore",
    officialUrl: "https://singaporegp.sg/",
  },
  {
    slug: "austin",
    name: "COTA Austin",
    officialName: "Circuit of the Americas",
    country: "United States",
    city: "Austin, Texas",
    region: "Americas",
    character: "40-meter uphill Turn 1 climb, Maggotts-inspired Esses, and triple-apex carousel",
    distance: "5.513 km",
    lapDistanceKm: 5.513,
    laps: 56,
    totalDistanceKm: 308.405,
    turns: "20 turns",
    turnCount: 20,
    lapType: "Modern elevation circuit",
    lapRecord: { time: "1:36.169", driver: "Charles Leclerc", year: 2019 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "High",
    tireStress: "High",
    gearShiftsPerLap: 56,
    intro: "A modern classic designed with homage to historic venues. Drivers sprint up a 40-meter vertical rise into a blind Turn 1 hairpin before plunging into a supersonic sequence of Esses mirroring Silverstone.",
    sectors: [
      { name: "Sector 1 (The Big Hill & Esses)", focus: "Turn 1 climb & Turns 3–6 flow", description: "Steep uphill braking into Turn 1, then high-g Esses loading car diffusers." },
      { name: "Sector 2 (Hairpin to 1km Straight)", focus: "Turn 11 hairpin & DRS drag", description: "Slow hairpin exit into the 1.1km back straight exceeding 335 km/h." },
      { name: "Sector 3 (Stadium & Quad Apex)", focus: "Turns 12–15 & multi-apex carousel", description: "Heavy braking into stadium arena followed by continuous high-g right-hand carousel." },
    ],
    lessons: [
      { title: "Blind apex commitment at Turn 1", text: "You cannot see the apex curb until 30 meters after beginning your braking phase." },
      { title: "Bumping over ground effect platforms", text: "Subsidence bumps can bottom out floor planks, disrupting aerodynamic suction." },
      { title: "Multiple overtaking lines in stadium", text: "Wide entry at Turn 12 allows late braking switchbacks into Turn 13." },
    ],
    fieldNote: "Austin offers immense elevation drama and a complete dynamic test of racecraft.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/united-states",
    officialUrl: "https://circuitoftheamericas.com/",
  },
  {
    slug: "mexico-city",
    name: "Mexico City",
    officialName: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    city: "Mexico City",
    region: "Americas",
    character: "2,285m high-altitude thin air, 360 km/h main straight, and Foro Sol baseball stadium",
    distance: "4.304 km",
    lapDistanceKm: 4.304,
    laps: 71,
    totalDistanceKm: 305.354,
    turns: "17 turns",
    turnCount: 17,
    lapType: "High-altitude stadium circuit",
    lapRecord: { time: "1:17.774", driver: "Valtteri Bottas", year: 2021 },
    drsZones: 3,
    overtakingDifficulty: "Low",
    downforceLevel: "Maximum",
    tireStress: "Medium",
    gearShiftsPerLap: 44,
    intro: "Perched 2,285 meters above sea level, the air is 22% less dense than at sea level. Teams run Monaco-spec maximum downforce wings, yet cars achieve Monza-rivaling top speeds of 355 km/h because of the minimal aerodynamic drag.",
    sectors: [
      { name: "Sector 1 (1.2km Main Straight & Chicane)", focus: "355 km/h stop into Turn 1", description: "Massive tow down the longest straight on the calendar into heavy 90° chicane." },
      { name: "Sector 2 (Flowing Esses)", focus: "High-speed esses with zero air", description: "Quick direction changes where thin air provides scarce aerodynamic grip." },
      { name: "Sector 3 (Foro Sol Stadium Arena)", focus: "Slow 60 km/h baseball stadium", description: "Driving through a 30,000-seat amphitheater surrounded by passionate fans." },
    ],
    lessons: [
      { title: "Engine and brake cooling starvation", text: "Thin air carries far fewer oxygen and cooling molecules, putting turbochargers and brakes at thermal limits." },
      { title: "Low aerodynamic grip in high-speed sweeps", text: "Despite massive wings, the car slides as if on ice through the Sector 2 esses." },
      { title: "The 800m slipstream draft to Turn 1", text: "Starting on pole position is dangerous; P2 and P3 have massive draft advantage into Turn 1." },
    ],
    fieldNote: "In Mexico, thin air creates a fascinating paradox of Monaco downforce wings delivering Monza top speeds.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/mexico",
    officialUrl: "https://www.autodromohermanosrodriguez.com/",
  },
  {
    slug: "interlagos",
    name: "Interlagos (São Paulo)",
    officialName: "Autódromo José Carlos Pace",
    country: "Brazil",
    city: "São Paulo",
    region: "Americas",
    character: "Anti-clockwise natural bowl, Senna S downhill plunge, and unpredictable micro-climates",
    distance: "4.309 km",
    lapDistanceKm: 4.309,
    laps: 71,
    totalDistanceKm: 305.879,
    turns: "15 turns",
    turnCount: 15,
    lapType: "Anti-clockwise amphitheater",
    lapRecord: { time: "1:10.540", driver: "Valtteri Bottas", year: 2018 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "High",
    gearShiftsPerLap: 42,
    intro: "One of motorsport's sacred grounds. Built between two subterranean lakes in São Paulo, Interlagos runs anti-clockwise with undulating natural contours, generating intense wheel-to-wheel battles and frequent wet-weather epics.",
    sectors: [
      { name: "Sector 1 (Senna 'S' to Curva do Sol)", focus: "Downhill left-right plunge", description: "Iconic downhill Senna S braking zone opening into the fast uphill Curva do Sol." },
      { name: "Sector 2 (Descida do Lago & Infield)", focus: "Lake descent & technical hairpin", description: "Heavy braking at Turn 4 into the tight, twisting Bico de Pato infield." },
      { name: "Sector 3 (Junção & Uphill Drag)", focus: "Turn 12 Junção to Main Straight", description: "Nailing the exit of Junção for the flat-out uphill sweep across the finish line." },
    ],
    lessons: [
      { title: "Mastering the Senna 'S' camber", text: "The track falls away to the left into Turn 1, making front-right lockups very common." },
      { title: "Anti-clockwise neck strain", text: "Left-hand turns strain driver neck muscles accustomed to clockwise circuits." },
      { title: "Rapid tropical micro-climate rain", text: "Clouds roll in over the bowl in minutes; one half of the track can be bone dry while the infield is flooded." },
    ],
    fieldNote: "Interlagos consistently produces the most dramatic racing on the calendar.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/brazil",
    officialUrl: "https://www.autodromodeinterlagos.com.br/",
  },
  {
    slug: "las-vegas",
    name: "Las Vegas",
    officialName: "Las Vegas Strip Circuit",
    country: "United States",
    city: "Las Vegas, Nevada",
    region: "Americas",
    character: "350 km/h blast down the iconic neon Las Vegas Boulevard under midnight temperatures",
    distance: "6.201 km",
    lapDistanceKm: 6.201,
    laps: 50,
    totalDistanceKm: 309.958,
    turns: "17 turns",
    turnCount: 17,
    lapType: "Ultra-fast night street circuit",
    lapRecord: { time: "1:35.490", driver: "Oscar Piastri", year: 2023 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Low",
    tireStress: "Medium",
    gearShiftsPerLap: 48,
    intro: "A glittering spectacle of speed. Cars blast down a 1.9km stretch of the world-famous Las Vegas Strip past the Bellagio fountains and Caesars Palace at 350 km/h in chilly desert midnight air.",
    sectors: [
      { name: "Sector 1 (Koval Lane to Sphere)", focus: "Tight chicane & Sphere 180°", description: "Technical complex sweeping around the colossal Sphere illuminated in neon." },
      { name: "Sector 2 (The Strip Drag)", focus: "1.9 km flat-out acceleration", description: "Pure speed along the Boulevard into the heavy braking zone at Turn 14." },
      { name: "Sector 3 (Harmon Avenue to Pit)", focus: "Quick direction shifts", description: "Fast acceleration onto Harmon Avenue past the massive paddock building." },
    ],
    lessons: [
      { title: "Cold desert tire graining", text: "Track surface temps can drop below 12°C, making tire warm-up and graining management crucial." },
      { title: "Braking after the 1.9km Strip blast", text: "Front carbon brake discs cool down drastically on the straight before a 350 km/h to 80 km/h stop." },
      { title: "Drafting slipstream battles", text: "The huge straight provides massive slipstream passes and counter-attacks lap after lap." },
    ],
    fieldNote: "Las Vegas pairs high-speed aerodynamic efficiency with chilly desert tire warm-up challenges.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/las-vegas",
    officialUrl: "https://www.f1lasvegasgp.com/",
  },
  {
    slug: "lusail",
    name: "Lusail (Qatar)",
    officialName: "Lusail International Circuit",
    country: "Qatar",
    city: "Lusail / Doha",
    region: "Middle East",
    character: "Flowing high-speed motorcycle layout with relentless medium-to-high speed lateral load",
    distance: "5.419 km",
    lapDistanceKm: 5.419,
    laps: 57,
    totalDistanceKm: 308.611,
    turns: "16 turns",
    turnCount: 16,
    lapType: "High-g flowing circuit",
    lapRecord: { time: "1:24.319", driver: "Max Verstappen", year: 2023 },
    drsZones: 1,
    overtakingDifficulty: "Moderate",
    downforceLevel: "High",
    tireStress: "Extreme",
    gearShiftsPerLap: 46,
    intro: "Originally engineered for MotoGP, Lusail is a relentless barrage of 4g and 5g high-speed medium sweeps. With virtually no slow hairpins, tires and driver necks are subjected to continuous lateral load.",
    sectors: [
      { name: "Sector 1 (Turn 1 to Turn 5)", focus: "Turn 1 braking & quick switches", description: "Heavy stop into Turn 1 followed by fast esses demanding supreme front-end agility." },
      { name: "Sector 2 (Turns 6–11 Flow)", focus: "Mid-speed lateral loading", description: "Continuous sweeping arcs through Turns 7, 8, 9, and 10 testing aerodynamic downforce." },
      { name: "Sector 3 (Triple-Apex Right-Hander)", focus: "Turns 12, 13, 14 carousel", description: "Fierce 5g triple-apex right sweep loading outside tires before the final corner." },
    ],
    lessons: [
      { title: "Pyramid curb tire damage", text: "Aggressive serrated curbs can puncture tire carcasses if drivers cut corners repeatedly." },
      { title: "Extreme physical g-force fatigue", text: "Sustained 5g loads with zero rest sections test driver core and neck stamina." },
      { title: "Mandatory stint limits", text: "Pirelli often imposes maximum lap counts per tire set due to extreme carcass fatigue." },
    ],
    fieldNote: "Lusail is a relentless high-speed centrifuge testing tire endurance and physical stamina.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/qatar",
    officialUrl: "https://www.lcsc.qa/",
  },
  {
    slug: "yas-marina",
    name: "Yas Marina",
    officialName: "Yas Marina Circuit",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    region: "Middle East",
    character: "Twilight season finale featuring Marina hotel complex and modified fast sweepers",
    distance: "5.281 km",
    lapDistanceKm: 5.281,
    laps: 58,
    totalDistanceKm: 306.183,
    turns: "16 turns",
    turnCount: 16,
    lapType: "Twilight permanent track",
    lapRecord: { time: "1:26.103", driver: "Max Verstappen", year: 2021 },
    drsZones: 2,
    overtakingDifficulty: "Moderate",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 56,
    intro: "The traditional twilight season finale. Races start under the golden Persian Gulf sunset and finish under floodlights around the illuminated W Abu Dhabi Hotel and multi-million dollar superyacht marina.",
    sectors: [
      { name: "Sector 1 (Turn 1 to West Hairpin)", focus: "High-speed Turn 2-3 into hairpin", description: "Fast initial corners leading into the modified wide West Hairpin." },
      { name: "Sector 2 (Dual DRS Straights)", focus: "Back straight & chicane", description: "Long back-to-back 330 km/h acceleration zones separated by a chicane." },
      { name: "Sector 3 (Marina Hotel Complex)", focus: "Technical 90° corners under hotel", description: "Twisting technical section passing directly underneath the illuminated hotel bridge." },
    ],
    lessons: [
      { title: "Track temperature drop through sunset", text: "As the sun sets, asphalt cools by over 10°C, shifting the car's balance from understeer to oversteer." },
      { title: "Traction out of modified Turn 9 banking", text: "The banked Turn 9 hairpin allows drivers to carry high momentum onto the back straight." },
      { title: "Pit exit tunnel navigation", text: "The pit lane passes through a unique subterranean tunnel under Turn 1." },
    ],
    fieldNote: "Yas Marina provides a stunning twilight backdrop with high tactical intrigue.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/abu-dhabi",
    officialUrl: "https://www.yasmarinacircuit.com/",
  },
  {
    slug: "shanghai",
    name: "Shanghai",
    officialName: "Shanghai International Circuit",
    country: "China",
    city: "Shanghai",
    region: "Asia-Pacific",
    character: "Endless 270° Snail Turn 1-4 and massive 1.2km back straight",
    distance: "5.451 km",
    lapDistanceKm: 5.451,
    laps: 56,
    totalDistanceKm: 305.066,
    turns: "16 turns",
    turnCount: 16,
    lapType: "Permanent modern facility",
    lapRecord: { time: "1:32.238", driver: "Michael Schumacher", year: 2004 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "High",
    gearShiftsPerLap: 52,
    intro: "Shaped like the Chinese character 'Shang' (上), this Hermann Tilke masterpiece is famous for its tightening 270-degree snail turn and a 1.2-kilometer back straight where slipstream battles thrive.",
    sectors: [
      { name: "Sector 1 (The Snail Turns 1–4)", focus: "Tightening spiral into hairpin", description: "Entering at 300 km/h and decelerating continuously while turning right, before a sharp left hairpin." },
      { name: "Sector 2 (Turns 6–10 Flow)", focus: "Mid-speed switchbacks", description: "Challenging acceleration zones testing rear traction and floor seal." },
      { name: "Sector 3 (1.2km Back Straight)", focus: "Long straight into Turn 14 stop", description: "Massive speed trap exceeding 340 km/h into the heaviest braking zone at Turn 14." },
    ],
    lessons: [
      { title: "Front-left tire graining in Turn 1", text: "The continuous right-hand spiral puts enormous continuous load on the front-left tire." },
      { title: "Braking from 340 km/h into Turn 14", text: "The hairpin at the end of the long straight offers prime overtaking if you brake at the 100m board." },
      { title: "Managing traction in changing wind", text: "The wide open flat plains make the back straight sensitive to gusting tailwinds." },
    ],
    fieldNote: "Shanghai tests front-tire longevity and straight-line aerodynamic efficiency.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/china",
    officialUrl: "https://www.sicracing.com/",
  },
  {
    slug: "miami",
    name: "Miami",
    officialName: "Miami International Autodrome",
    country: "United States",
    city: "Miami Gardens, Florida",
    region: "Americas",
    character: "Stadium street hybrid with high-speed Marina sweepers and technical bridge chicane",
    distance: "5.412 km",
    lapDistanceKm: 5.412,
    laps: 57,
    totalDistanceKm: 308.326,
    turns: "19 turns",
    turnCount: 19,
    lapType: "Stadium hybrid street circuit",
    lapRecord: { time: "1:29.708", driver: "Max Verstappen", year: 2023 },
    drsZones: 3,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 54,
    intro: "Weaving around Hard Rock Stadium in Miami Gardens, this high-energy hybrid circuit features fast flowing sweeps through the Marina and a narrow, tricky uphill chicane underneath highway overpasses.",
    sectors: [
      { name: "Sector 1 (Stadium Esses)", focus: "High-speed sweeping flow", description: "Quick direction changes through Turns 4, 5, 6, and 7 around the stadium perimeter." },
      { name: "Sector 2 (Overpass Chicane)", focus: "Tight Turns 14–15 uphill chicane", description: "Curb-hopping chicane with blind crest and tight barrier clearances." },
      { name: "Sector 3 (1.3km Back Straight)", focus: "Long straight into Turn 17 hairpin", description: "DRS speed trap reaching 345 km/h before heavy braking into the final hairpin." },
    ],
    lessons: [
      { title: "Surviving the Turn 14-15 chicane", text: "Hitting the curbs wrong can launch the car into the concrete wall under the bridge." },
      { title: "Track surface evolution", text: "Grip increases dramatically over the weekend as rubber gets embedded into the Florida aggregate." },
      { title: "Triple DRS overtaking zones", text: "Three distinct DRS straights create frequent lead changes." },
    ],
    fieldNote: "Miami brings vibrant American festival culture to a technical, high-speed stadium track.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/miami",
    officialUrl: "https://f1miamigp.com/",
  },
  {
    slug: "monaco",
    name: "Monaco",
    officialName: "Circuit de Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    region: "Europe",
    character: "The crown jewel: racing through narrow Riviera streets inches from barriers",
    distance: "3.337 km",
    lapDistanceKm: 3.337,
    laps: 78,
    totalDistanceKm: 260.286,
    turns: "19 turns",
    turnCount: 19,
    lapType: "Historic street circuit",
    lapRecord: { time: "1:12.909", driver: "Lewis Hamilton", year: 2021 },
    drsZones: 1,
    overtakingDifficulty: "Extreme",
    downforceLevel: "Maximum",
    tireStress: "Low",
    gearShiftsPerLap: 80,
    intro: "Motorsport's most prestigious and unforgiving challenge. Weaving between the luxury yachts of Port Hercule and the glamorous Casino Square, Monaco permits zero mistakes. Qualifying on Saturday dictates 90% of the race result.",
    sectors: [
      { name: "Sector 1 (Sainte Dévote to Casino)", focus: "Uphill Beau Rivage & Casino", description: "Braking into Sainte Dévote, accelerating uphill past Hotel de Paris into Casino Square." },
      { name: "Sector 2 (Mirabeau to Tunnel)", focus: "Fairmont Hairpin & 290 km/h Tunnel", description: "The slowest corner in F1 (45 km/h) followed by the blind acoustic roar of the Tunnel." },
      { name: "Sector 3 (Swimming Pool & Rascasse)", focus: "Chicane & historic Rascasse", description: "High-speed precision through the chicane and around the Swimming Pool barriers." },
    ],
    lessons: [
      { title: "Saturday qualifying is everything", text: "Overtaking on Sunday is virtually impossible without strategy or weather disruption." },
      { title: "Steering lock at Fairmont Hairpin", text: "Teams run special modified steering racks to negotiate the extreme 45° hairpin angle." },
      { title: "Tunnel transition lighting", text: "Eyes take milliseconds to adjust transitioning from bright Mediterranean sun into the dark tunnel." },
    ],
    fieldNote: "Monaco is a sensory overload where precision separates legends from the barriers.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/monaco",
    officialUrl: "https://www.acm.mc/en/",
  },
  {
    slug: "barcelona",
    name: "Barcelona (Catalunya)",
    officialName: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    city: "Montmeló / Barcelona",
    region: "Europe",
    character: "The ultimate aerodynamic benchmark with high-speed Turn 3 and fast final sweep",
    distance: "4.657 km",
    lapDistanceKm: 4.657,
    laps: 66,
    totalDistanceKm: 307.236,
    turns: "14 turns",
    turnCount: 14,
    lapType: "Aero benchmark circuit",
    lapRecord: { time: "1:16.330", driver: "Max Verstappen", year: 2023 },
    drsZones: 2,
    overtakingDifficulty: "Moderate",
    downforceLevel: "High",
    tireStress: "High",
    gearShiftsPerLap: 48,
    intro: "The definitive test of a Formula 1 chassis. With long high-speed right-handers and rapid direction shifts, Catalunya exposes every aerodynamic and mechanical flaw in a racecar.",
    sectors: [
      { name: "Sector 1 (Elf Chicane & Turn 3)", focus: "Turn 1-2 stop into long Turn 3", description: "Braking into Elf chicane followed by the punishing 4.5g acceleration through Turn 3." },
      { name: "Sector 2 (Campsa to La Caixa)", focus: "Blind uphill Campsa & stadium", description: "Uphill 240 km/h Campsa right-hander into the technical Sector 2 descent." },
      { name: "Sector 3 (Original Fast Final Sweep)", focus: "Turns 13–14 without chicane", description: "Flat-out high-speed right-hand sweeps launching cars onto the 1km main straight." },
    ],
    lessons: [
      { title: "Front-left tire thermal torture in Turn 3", text: "Sustained high lateral loading cooks the front-left shoulder rubber." },
      { title: "Dirty air wake following", text: "High downforce corners make following closely difficult without degrading front tires." },
      { title: "Wind shifts over the hill", text: "Afternoon wind changes direction at Turn 1, altering braking reference points." },
    ],
    fieldNote: "If a car is fast in Barcelona, it is fast everywhere.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/spain",
    officialUrl: "https://www.circuitcat.com/en/",
  },
  {
    slug: "montreal",
    name: "Montreal",
    officialName: "Circuit Gilles-Villeneuve",
    country: "Canada",
    city: "Montreal, Quebec",
    region: "Americas",
    character: "Stop-and-go curb hopping on Île Notre-Dame ending at the Wall of Champions",
    distance: "4.361 km",
    lapDistanceKm: 4.361,
    laps: 70,
    totalDistanceKm: 305.270,
    turns: "14 turns",
    turnCount: 14,
    lapType: "Semi-permanent parkland track",
    lapRecord: { time: "1:13.078", driver: "Valtteri Bottas", year: 2019 },
    drsZones: 3,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 52,
    intro: "Located on a man-made island in the Saint Lawrence River, Montreal is a high-speed stop-and-go challenge demanding aggressive curb usage, huge braking power, and respect for the infamous 'Wall of Champions'.",
    sectors: [
      { name: "Sector 1 (Virage Senna & Chicane)", focus: "Turn 1-2 hairpin switchback", description: "Tight Virage Senna loop opening into the high-speed chicane sequence." },
      { name: "Sector 2 (Casino Straight to Hairpin)", focus: "Chicanes into L'Épingle hairpin", description: "Chicane curb-bashing into the slow 65 km/h L'Épingle hairpin grandstand." },
      { name: "Sector 3 (Wall of Champions)", focus: "330 km/h straight into final chicane", description: "Flat out down the Droit du Casino into the chicane where the outside wall awaits." },
    ],
    lessons: [
      { title: "Brake wear and fluid boiling", text: "Montreal has four stops from 300+ km/h, making brake temperature management critical." },
      { title: "Riding curbs aggressively", text: "Gaining lap time requires riding curb apexes aggressively to shorten corner radius." },
      { title: "Respecting the Wall of Champions", text: "Taking 2 cm too much curb into the final chicane bounces you straight into the concrete." },
    ],
    fieldNote: "Montreal rewards brave braking, agile curb control, and tactical DRS slipstreaming.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/canada",
    officialUrl: "https://www.gpcanada.ca/en/",
  },
  {
    slug: "spielberg",
    name: "Spielberg (Red Bull Ring)",
    officialName: "Red Bull Ring",
    country: "Austria",
    city: "Spielberg, Styria",
    region: "Europe",
    character: "Shortest lap time in F1 (64s), steep Styrian hillside climbs and 3 DRS zones",
    distance: "4.318 km",
    lapDistanceKm: 4.318,
    laps: 71,
    totalDistanceKm: 306.452,
    turns: "10 turns",
    turnCount: 10,
    lapType: "Short alpine amphitheater",
    lapRecord: { time: "1:05.619", driver: "Carlos Sainz", year: 2020 },
    drsZones: 3,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 40,
    intro: "Nestled in the picturesque Styrian Alps, the Red Bull Ring features only 10 corners and produces sub-65-second lap times. Three consecutive DRS zones generate constant wheel-to-wheel overtaking.",
    sectors: [
      { name: "Sector 1 (Niki Lauda Kurve to Remus)", focus: "Uphill drag to Turn 3 hairpin", description: "Steep uphill acceleration into the heavy first-gear Turn 3 braking point." },
      { name: "Sector 2 (Schlossgold & Rauch)", focus: "Downhill sweeps at Turns 4–7", description: "Downhill braking into Turn 4 followed by fast sweeping left-handers." },
      { name: "Sector 3 (Jochen Rindt to Finish)", focus: "Fast right-hand final corners", description: "Two high-speed right-handers testing track limits at the exit of Turn 10." },
    ],
    lessons: [
      { title: "Turn 3 hairpin divebombs", text: "The uphill braking zone allows aggressive divebomb passes with good visibility." },
      { title: "Track limits at Turns 9 & 10", text: "Exceeding the white line by millimeters deletes qualifying laps immediately." },
      { title: "Alpine weather storms", text: "Mountain storm cells can sweep across the valley in minutes." },
    ],
    fieldNote: "The Red Bull Ring's short, punchy layout packs intense drama into every 64-second lap.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/austria",
    officialUrl: "https://www.redbullring.com/en/",
  },
  {
    slug: "silverstone",
    name: "Silverstone",
    officialName: "Silverstone Circuit",
    country: "Great Britain",
    city: "Silverstone, Northamptonshire",
    region: "Europe",
    character: "Home of British motorsport: supersonic Copse, Maggotts-Becketts, and Stowe",
    distance: "5.891 km",
    lapDistanceKm: 5.891,
    laps: 52,
    totalDistanceKm: 306.198,
    turns: "18 turns",
    turnCount: 18,
    lapType: "High-speed historic airfield",
    lapRecord: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "High",
    tireStress: "Extreme",
    gearShiftsPerLap: 48,
    intro: "The birthplace of Formula 1 World Championship racing in 1950. Silverstone is a supersonic temple of high-speed downforce where drivers experience over 5g in the legendary Maggotts-Becketts-Chapel complex.",
    sectors: [
      { name: "Sector 1 (Abbey, Farm, Village, The Loop)", focus: "Flat-out Abbey into tight Loop", description: "290 km/h Abbey right-hander into the technical Village chicane and Loop hairpin." },
      { name: "Sector 2 (Copse & Maggotts-Becketts)", focus: "290 km/h Copse & 5g S-bends", description: "Copse taken with minimal lift into the most iconic high-g switchbacks in racing." },
      { name: "Sector 3 (Hangar Straight, Stowe & Club)", focus: "330 km/h Hangar blast to Stowe", description: "Hangar Straight into high-speed Stowe right-hander and Vale-Club chicane." },
    ],
    lessons: [
      { title: "Commitment through Copse corner", text: "Taken at nearly 290 km/h in 7th gear with a feather touch on the throttle." },
      { title: "Extreme lateral tire fatigue", text: "Silverstone exerts the highest sustained lateral loads of any circuit on the calendar." },
      { title: "Unpredictable British crosswinds", text: "Built on an open World War II airfield, sudden gusts unbalance aerodynamic wings." },
    ],
    fieldNote: "Silverstone provides pure high-speed aerodynamic adrenaline in front of passionate fans.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/great-britain",
    officialUrl: "https://www.silverstone.co.uk/",
  },
  {
    slug: "spa",
    name: "Spa-Francorchamps",
    officialName: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    city: "Stavelot / Spa, Ardennes",
    region: "Europe",
    character: "The Ardennes rollercoaster: Eau Rouge-Raidillon, Kemmel Straight, and Pouhon",
    distance: "7.004 km",
    lapDistanceKm: 7.004,
    laps: 44,
    totalDistanceKm: 308.052,
    turns: "19 turns",
    turnCount: 19,
    lapType: "Longest circuit on calendar",
    lapRecord: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    drsZones: 2,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "High",
    gearShiftsPerLap: 44,
    intro: "Revered by every racing driver on Earth. Spanning 7 kilometers across the undulating Ardennes hills, Spa combines extreme vertical compression through Eau Rouge and Raidillon with the supersonic 300 km/h Pouhon double-left.",
    sectors: [
      { name: "Sector 1 (La Source & Eau Rouge-Raidillon)", focus: "Hairpin stop & 17% compression", description: "Tight La Source hairpin into the blind uphill crest of Eau Rouge and Raidillon." },
      { name: "Sector 2 (Les Combes, Pouhon, Stavelot)", focus: "Kemmel slipstream & 290 km/h Pouhon", description: "Overtaking into Les Combes followed by the fearsome downhill Pouhon double-left." },
      { name: "Sector 3 (Blanchimont to Bus Stop)", focus: "315 km/h Blanchimont into chicane", description: "Supersonic Blanchimont sweep into the heavy braking Bus Stop chicane." },
    ],
    lessons: [
      { title: "Eau Rouge vertical g-compression", text: "Bottom of Eau Rouge pushes driver into cockpit with 4g vertical load before going light over Raidillon." },
      { title: "The Spa microclimate paradox", text: "At 7km long, it can be pouring rain at Blanchimont while bone dry at La Source." },
      { title: "Aero setup dilemma", text: "Low downforce wins on Kemmel straight; high downforce is needed in Sector 2's Pouhon." },
    ],
    fieldNote: "Spa-Francorchamps is the ultimate driver's circuit, where courage meets elevation.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/belgium",
    officialUrl: "https://www.spa-francorchamps.be/en/",
  },
  {
    slug: "hungaroring",
    name: "Hungaroring",
    officialName: "Hungaroring",
    country: "Hungary",
    city: "Mogyoród / Budapest",
    region: "Europe",
    character: "Monaco without the walls: dusty, twisty, relentless and blazing hot",
    distance: "4.381 km",
    lapDistanceKm: 4.381,
    laps: 70,
    totalDistanceKm: 306.630,
    turns: "14 turns",
    turnCount: 14,
    lapType: "Twisting amphitheater bowl",
    lapRecord: { time: "1:16.627", driver: "Lewis Hamilton", year: 2020 },
    drsZones: 2,
    overtakingDifficulty: "High",
    downforceLevel: "Maximum",
    tireStress: "Medium",
    gearShiftsPerLap: 50,
    intro: "Often nicknamed 'Monaco without the buildings'. Built in a natural valley outside Budapest, Hungaroring is a non-stop sequence of 14 medium-to-slow speed corners where qualifying and strategic undercut timing reign supreme.",
    sectors: [
      { name: "Sector 1 (Turn 1 Downhill to Turn 3)", focus: "Main straight & downhill hairpin", description: "Heavy downhill braking into Turn 1, followed by the sweeping off-camber Turn 2 and 3." },
      { name: "Sector 2 (Turns 4–11 Valley Flow)", focus: "Fast Turn 4 crest & chicane", description: "Blind uphill crest at Turn 4 into the tight chicane and continuous mid-sector turns." },
      { name: "Sector 3 (Turns 12–14 Arena)", focus: "90° Turn 12 into long 180° final turn", description: "Sharp Turn 12 right-hander into the double-apex final corner launching onto the straight." },
    ],
    lessons: [
      { title: "Qualifying track position value", text: "Difficult overtaking makes starting on the front two rows vital." },
      { title: "Dust off-line on Friday", text: "Asphalt is rarely used during the year, making off-line grip dangerously low initially." },
      { title: "Overheating cockpits in August", text: "Summer heat in Budapest often pushes ambient temps above 35°C." },
    ],
    fieldNote: "Hungaroring demands maximum downforce and precise rhythm through unbroken corners.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/hungary",
    officialUrl: "https://hungaroring.hu/en",
  },
  {
    slug: "albert-park",
    name: "Albert Park (Melbourne)",
    officialName: "Albert Park Circuit",
    country: "Australia",
    city: "Melbourne, Victoria",
    region: "Asia-Pacific",
    character: "Lakeside parkland sweeps, high-speed chicanes and festival atmosphere",
    distance: "5.278 km",
    lapDistanceKm: 5.278,
    laps: 58,
    totalDistanceKm: 306.124,
    turns: "14 turns",
    turnCount: 14,
    lapType: "Semi-permanent parkland track",
    lapRecord: { time: "1:19.813", driver: "Charles Leclerc", year: 2024 },
    drsZones: 4,
    overtakingDifficulty: "Low",
    downforceLevel: "Medium",
    tireStress: "Medium",
    gearShiftsPerLap: 52,
    intro: "Flowing around Melbourne's picturesque Albert Park lake, this fast parkland track features high-speed flowing sweeps and four distinct DRS zones.",
    sectors: [
      { name: "Sector 1 (Turns 1–5)", focus: "Turn 1-2 chicane & lakeside sweeps", description: "Heavy braking into Turn 1 chicane opening into the sweeping right-hand Turn 3." },
      { name: "Sector 2 (Turns 6–10 Lakeside Blast)", focus: "270 km/h lakeside curve", description: "Flat-out lakeside curve replacing the old chicane into the high-speed Turn 9-10 complex." },
      { name: "Sector 3 (Turns 11–14)", focus: "Fast Turn 11-12 & stadium finish", description: "High-speed chicane at Turn 11-12 leading into the stadium arena corners." },
    ],
    lessons: [
      { title: "Low-sun glare in late afternoon", text: "Late afternoon autumn sun drops low, blinding drivers into Turn 1." },
      { title: "Rapid track evolution over park roads", text: "Standard public road asphalt gains huge grip as racing rubber is laid down." },
      { title: "Safety car frequency", text: "Narrow barriers and high average speeds mean safety cars are common." },
    ],
    fieldNote: "Albert Park pairs parkland scenery with thrilling high-speed cornering.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/australia",
    officialUrl: "https://www.grandprix.com.au/",
  },
  {
    slug: "suzuka",
    name: "Suzuka",
    officialName: "Suzuka International Racing Course",
    country: "Japan",
    city: "Suzuka, Mie Prefecture",
    region: "Asia-Pacific",
    character: "Figure-8 crossover masterpiece: Esses, Degner chicanes, Spoon, and 130R",
    distance: "5.807 km",
    lapDistanceKm: 5.807,
    laps: 53,
    totalDistanceKm: 307.471,
    turns: "18 turns",
    turnCount: 18,
    lapType: "Figure-8 crossover circuit",
    lapRecord: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    drsZones: 1,
    overtakingDifficulty: "Moderate",
    downforceLevel: "High",
    tireStress: "Extreme",
    gearShiftsPerLap: 50,
    intro: "The definitive driver's temple. Designed by John Hugenholtz as a Honda test track, Suzuka is the only figure-8 crossover track in Formula 1. The flowing S-Curves, double Degners, Spoon Curve, and supersonic 130R test chassis balance and driver courage.",
    sectors: [
      { name: "Sector 1 (First Sector S-Curves)", focus: "Turn 1-2 into connected Esses", description: "Downhill Turn 1 into five linked high-g esses where rhythm is everything." },
      { name: "Sector 2 (Degners, Crossover, Hairpin, Spoon)", focus: "Degner 1-2 & Spoon curve", description: "Brave curb-riding into Degner 1 and 2, passing under the crossover into the long Spoon." },
      { name: "Sector 3 (130R to Casio Triangle)", focus: "310 km/h 130R into final chicane", description: "Supersonic 130R left-hander taken flat out into the Casio Triangle chicane." },
    ],
    lessons: [
      { title: "Rhythm through the Sector 1 Esses", text: "A mistake in Turn 3 ruins your line for Turns 4, 5, 6, and 7." },
      { title: "Commitment into Degner 1", text: "Taken at 250 km/h; dipping a tire onto the outside grass results in instant barrier contact." },
      { title: "Front tire thermal degradation in Spoon", text: "The long double-apex left-hander cooks the front-right tire shoulder." },
    ],
    fieldNote: "Suzuka is the purest test of aerodynamic balance and driver feel in motorsport.",
    sourceUrl: "https://www.formula1.com/en/racing/2026/japan",
    officialUrl: "https://www.suzukacircuit.jp/en/",
  },
];
import { stories, type Story } from "./data/stories";
export { stories, type Story };



export type Driver = {
  id: string;
  code: string;
  name: string;
  number: number;
  team: string;
  country: string;
  points: number;
  wins: number;
  podiums: number;
  poles: number;
  fastestLaps: number;
  rating: number;
  teammateH2HQuali: string;
  teammateH2HRace: string;
  drivingStyle: string;
  careerChampionships: number;
};

export type Team = {
  id: string;
  name: string;
  base: string;
  engine: string;
  points: number;
  wins: number;
  podiums: number;
  leadDrivers: string;
  chassisName: string;
};

// 2026 ACTIVE SEASON STANDINGS (Current Round 12 Zandvoort / Live Championship)
export const drivers2026: Driver[] = [
  {
    id: "antonelli",
    code: "ANT",
    name: "Andrea Kimi Antonelli",
    number: 12,
    team: "Mercedes-AMG Petronas",
    country: "Italy",
    points: 224,
    wins: 6,
    podiums: 10,
    poles: 5,
    fastestLaps: 4,
    rating: 94,
    teammateH2HQuali: "8 - 4 vs RUS",
    teammateH2HRace: "7 - 3 vs RUS",
    drivingStyle: "Ultra-precise front-end feel with remarkable high-speed corner commitment.",
    careerChampionships: 0,
  },
  {
    id: "hamilton",
    code: "HAM",
    name: "Lewis Hamilton",
    number: 44,
    team: "Scuderia Ferrari HP",
    country: "Great Britain",
    points: 171,
    wins: 1,
    podiums: 7,
    poles: 2,
    fastestLaps: 2,
    rating: 95,
    teammateH2HQuali: "6 - 6 vs LEC",
    teammateH2HRace: "7 - 5 vs LEC",
    drivingStyle: "Master of tire preservation, wet weather mastery and race-pace management.",
    careerChampionships: 7,
  },
  {
    id: "russell",
    code: "RUS",
    name: "George Russell",
    number: 63,
    team: "Mercedes-AMG Petronas",
    country: "Great Britain",
    points: 168,
    wins: 2,
    podiums: 6,
    poles: 2,
    fastestLaps: 1,
    rating: 93,
    teammateH2HQuali: "4 - 8 vs ANT",
    teammateH2HRace: "3 - 7 vs ANT",
    drivingStyle: "Aggressive qualifying specialist with rapid tire warm-up capability.",
    careerChampionships: 0,
  },
  {
    id: "leclerc",
    code: "LEC",
    name: "Charles Leclerc",
    number: 16,
    team: "Scuderia Ferrari HP",
    country: "Monaco",
    points: 145,
    wins: 1,
    podiums: 5,
    poles: 3,
    fastestLaps: 2,
    rating: 94,
    teammateH2HQuali: "6 - 6 vs HAM",
    teammateH2HRace: "5 - 7 vs HAM",
    drivingStyle: "Extraordinary one-lap qualifying pace and brave late braking.",
    careerChampionships: 0,
  },
  {
    id: "norris",
    code: "NOR",
    name: "Lando Norris",
    number: 4,
    team: "McLaren Formula 1 Team",
    country: "Great Britain",
    points: 134,
    wins: 1,
    podiums: 4,
    poles: 1,
    fastestLaps: 1,
    rating: 92,
    teammateH2HQuali: "7 - 5 vs PIA",
    teammateH2HRace: "6 - 5 vs PIA",
    drivingStyle: "Smooth car rotation with high minimum mid-corner apex speed.",
    careerChampionships: 1,
  },
  {
    id: "verstappen",
    code: "VER",
    name: "Max Verstappen",
    number: 1,
    team: "Oracle Red Bull Racing",
    country: "Netherlands",
    points: 112,
    wins: 1,
    podiums: 3,
    poles: 1,
    fastestLaps: 1,
    rating: 97,
    teammateH2HQuali: "11 - 1 vs HAD",
    teammateH2HRace: "10 - 1 vs HAD",
    drivingStyle: "Pointy front-axle tolerance with supreme wheel-to-wheel combat instinct.",
    careerChampionships: 4,
  },
  {
    id: "piastri",
    code: "PIA",
    name: "Oscar Piastri",
    number: 81,
    team: "McLaren Formula 1 Team",
    country: "Australia",
    points: 96,
    wins: 1,
    podiums: 3,
    poles: 0,
    fastestLaps: 1,
    rating: 91,
    teammateH2HQuali: "5 - 7 vs NOR",
    teammateH2HRace: "5 - 6 vs NOR",
    drivingStyle: "Composed under pressure with exceptional tire thermal discipline.",
    careerChampionships: 0,
  },
  {
    id: "hadjar",
    code: "HAD",
    name: "Isack Hadjar",
    number: 6,
    team: "Oracle Red Bull Racing",
    country: "France",
    points: 68,
    wins: 0,
    podiums: 1,
    poles: 0,
    fastestLaps: 0,
    rating: 86,
    teammateH2HQuali: "1 - 11 vs VER",
    teammateH2HRace: "1 - 10 vs VER",
    drivingStyle: "High-aggression rookie with bold braking maneuvers.",
    careerChampionships: 0,
  },
  {
    id: "alonso",
    code: "ALO",
    name: "Fernando Alonso",
    number: 14,
    team: "Aston Martin Aramco F1 Team",
    country: "Spain",
    points: 54,
    wins: 0,
    podiums: 1,
    poles: 0,
    fastestLaps: 0,
    rating: 91,
    teammateH2HQuali: "10 - 2 vs STR",
    teammateH2HRace: "9 - 2 vs STR",
    drivingStyle: "Unrivaled strategic race reading, adapting instantly to handling issues.",
    careerChampionships: 2,
  },
  {
    id: "gasly",
    code: "GAS",
    name: "Pierre Gasly",
    number: 10,
    team: "BWT Alpine F1 Team",
    country: "France",
    points: 43,
    wins: 0,
    podiums: 1,
    poles: 0,
    fastestLaps: 0,
    rating: 88,
    teammateH2HQuali: "8 - 4 vs DOO",
    teammateH2HRace: "8 - 4 vs DOO",
    drivingStyle: "Feisty braker with high qualifying commitment.",
    careerChampionships: 0,
  },
  {
    id: "lawson",
    code: "LAW",
    name: "Liam Lawson",
    number: 30,
    team: "Visa Cash App RB",
    country: "New Zealand",
    points: 43,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    rating: 87,
    teammateH2HQuali: "6 - 6 vs TSU",
    teammateH2HRace: "6 - 6 vs TSU",
    drivingStyle: "Decisive overtaking and resolute defensive positioning.",
    careerChampionships: 0,
  },
  {
    id: "sainz",
    code: "SAI",
    name: "Carlos Sainz",
    number: 55,
    team: "Williams Racing",
    country: "Spain",
    points: 38,
    wins: 0,
    podiums: 0,
    poles: 0,
    fastestLaps: 0,
    rating: 90,
    teammateH2HQuali: "8 - 4 vs ALB",
    teammateH2HRace: "7 - 5 vs ALB",
    drivingStyle: "Master strategist with exceptional adaptability in mixed weather.",
    careerChampionships: 0,
  },
];

export const teams2026: Team[] = [
  { id: "mercedes", name: "Mercedes-AMG Petronas", base: "Brackley, UK", engine: "Mercedes-AMG", points: 392, wins: 8, podiums: 16, leadDrivers: "K. Antonelli & G. Russell", chassisName: "F1 W17" },
  { id: "ferrari", name: "Scuderia Ferrari HP", base: "Maranello, Italy", engine: "Ferrari 067/2", points: 316, wins: 2, podiums: 12, leadDrivers: "L. Hamilton & C. Leclerc", chassisName: "SF-26" },
  { id: "mclaren", name: "McLaren Formula 1 Team", base: "Woking, UK", engine: "Mercedes-AMG", points: 230, wins: 2, podiums: 7, leadDrivers: "L. Norris & O. Piastri", chassisName: "MCL40" },
  { id: "redbull", name: "Oracle Red Bull Racing", base: "Milton Keynes, UK", engine: "Red Bull Ford Powertrains", points: 180, wins: 1, podiums: 4, leadDrivers: "M. Verstappen & I. Hadjar", chassisName: "RB22" },
  { id: "astonmartin", name: "Aston Martin Aramco", base: "Silverstone, UK", engine: "Honda HRC", points: 72, wins: 0, podiums: 1, leadDrivers: "F. Alonso & L. Stroll", chassisName: "AMR26" },
  { id: "alpine", name: "BWT Alpine F1 Team", base: "Enstone, UK", engine: "Mercedes-AMG", points: 62, wins: 0, podiums: 1, leadDrivers: "P. Gasly & J. Doohan", chassisName: "A526" },
  { id: "rb", name: "Visa Cash App RB", base: "Faenza, Italy", engine: "Red Bull Ford Powertrains", points: 58, wins: 0, podiums: 0, leadDrivers: "L. Lawson & Y. Tsunoda", chassisName: "VCARB 03" },
  { id: "williams", name: "Williams Racing", base: "Grove, UK", engine: "Mercedes-AMG", points: 46, wins: 0, podiums: 0, leadDrivers: "C. Sainz & A. Albon", chassisName: "FW48" },
  { id: "haas", name: "MoneyGram Haas F1 Team", base: "Kannapolis, USA", engine: "Ferrari", points: 32, wins: 0, podiums: 0, leadDrivers: "O. Bearman & E. Ocon", chassisName: "VF-26" },
  { id: "audi", name: "Audi Revolut F1 Team", base: "Hinwil, Switzerland", engine: "Audi F1 Power Unit", points: 12, wins: 0, podiums: 0, leadDrivers: "N. Hülkenberg & G. Bortoleto", chassisName: "Audi R26" },
];

// 2024 OFFICIAL CHAMPIONSHIP STANDINGS (Historical Master Archive)
export const drivers2024: Driver[] = [
  {
    id: "verstappen-2024",
    code: "VER",
    name: "Max Verstappen",
    number: 1,
    team: "Oracle Red Bull Racing",
    country: "Netherlands",
    points: 437,
    wins: 9,
    podiums: 14,
    poles: 8,
    fastestLaps: 5,
    rating: 98,
    teammateH2HQuali: "23 - 1 vs PER",
    teammateH2HRace: "21 - 3 vs PER",
    drivingStyle: "Dominant front-axle sharpness and peerless race execution.",
    careerChampionships: 4,
  },
  {
    id: "norris-2024",
    code: "NOR",
    name: "Lando Norris",
    number: 4,
    team: "McLaren Formula 1 Team",
    country: "Great Britain",
    points: 374,
    wins: 4,
    podiums: 12,
    poles: 8,
    fastestLaps: 4,
    rating: 95,
    teammateH2HQuali: "16 - 8 vs PIA",
    teammateH2HRace: "15 - 9 vs PIA",
    drivingStyle: "Smooth corner entry and explosive medium-speed pace.",
    careerChampionships: 0,
  },
  {
    id: "leclerc-2024",
    code: "LEC",
    name: "Charles Leclerc",
    number: 16,
    team: "Scuderia Ferrari HP",
    country: "Monaco",
    points: 356,
    wins: 3,
    podiums: 13,
    poles: 3,
    fastestLaps: 3,
    rating: 95,
    teammateH2HQuali: "15 - 9 vs SAI",
    teammateH2HRace: "13 - 11 vs SAI",
    drivingStyle: "Unmatched one-lap qualifying magic and fearless late-braking.",
    careerChampionships: 0,
  },
  {
    id: "piastri-2024",
    code: "PIA",
    name: "Oscar Piastri",
    number: 81,
    team: "McLaren Formula 1 Team",
    country: "Australia",
    points: 292,
    wins: 2,
    podiums: 9,
    poles: 1,
    fastestLaps: 2,
    rating: 92,
    teammateH2HQuali: "8 - 16 vs NOR",
    teammateH2HRace: "9 - 15 vs NOR",
    drivingStyle: "Ice-cold poise and tire preservation.",
    careerChampionships: 0,
  },
  {
    id: "sainz-2024",
    code: "SAI",
    name: "Carlos Sainz",
    number: 55,
    team: "Scuderia Ferrari HP",
    country: "Spain",
    points: 290,
    wins: 2,
    podiums: 8,
    poles: 2,
    fastestLaps: 1,
    rating: 92,
    teammateH2HQuali: "9 - 15 vs LEC",
    teammateH2HRace: "11 - 13 vs LEC",
    drivingStyle: "Smooth tire management and brilliant tactical acumen.",
    careerChampionships: 0,
  },
  {
    id: "russell-2024",
    code: "RUS",
    name: "George Russell",
    number: 63,
    team: "Mercedes-AMG Petronas",
    country: "Great Britain",
    points: 245,
    wins: 2,
    podiums: 4,
    poles: 4,
    fastestLaps: 2,
    rating: 93,
    teammateH2HQuali: "17 - 7 vs HAM",
    teammateH2HRace: "13 - 11 vs HAM",
    drivingStyle: "Qualifying speed and rapid early-lap pace.",
    careerChampionships: 0,
  },
  {
    id: "hamilton-2024",
    code: "HAM",
    name: "Lewis Hamilton",
    number: 44,
    team: "Mercedes-AMG Petronas",
    country: "Great Britain",
    points: 223,
    wins: 2,
    podiums: 4,
    poles: 0,
    fastestLaps: 2,
    rating: 95,
    teammateH2HQuali: "7 - 17 vs RUS",
    teammateH2HRace: "11 - 13 vs RUS",
    drivingStyle: "Legendary racecraft and rain mastery.",
    careerChampionships: 7,
  },
  {
    id: "perez-2024",
    code: "PER",
    name: "Sergio Perez",
    number: 11,
    team: "Oracle Red Bull Racing",
    country: "Mexico",
    points: 152,
    wins: 0,
    podiums: 4,
    poles: 0,
    fastestLaps: 1,
    rating: 86,
    teammateH2HQuali: "1 - 23 vs VER",
    teammateH2HRace: "3 - 21 vs VER",
    drivingStyle: "Rear tire management on street tracks.",
    careerChampionships: 0,
  },
];

export const teams2024: Team[] = [
  { id: "mclaren-2024", name: "McLaren Formula 1 Team", base: "Woking, UK", engine: "Mercedes-AMG", points: 666, wins: 6, podiums: 21, leadDrivers: "L. Norris & O. Piastri", chassisName: "MCL38" },
  { id: "ferrari-2024", name: "Scuderia Ferrari HP", base: "Maranello, Italy", engine: "Ferrari", points: 652, wins: 5, podiums: 21, leadDrivers: "C. Leclerc & C. Sainz", chassisName: "SF-24" },
  { id: "redbull-2024", name: "Oracle Red Bull Racing", base: "Milton Keynes, UK", engine: "Honda RBPT", points: 589, wins: 9, podiums: 18, leadDrivers: "M. Verstappen & S. Perez", chassisName: "RB20" },
  { id: "mercedes-2024", name: "Mercedes-AMG Petronas", base: "Brackley, UK", engine: "Mercedes-AMG", points: 468, wins: 4, podiums: 8, leadDrivers: "G. Russell & L. Hamilton", chassisName: "F1 W15" },
  { id: "astonmartin-2024", name: "Aston Martin Aramco", base: "Silverstone, UK", engine: "Mercedes-AMG", points: 94, wins: 0, podiums: 0, leadDrivers: "F. Alonso & L. Stroll", chassisName: "AMR24" },
  { id: "alpine-2024", name: "BWT Alpine F1 Team", base: "Enstone, UK", engine: "Renault", points: 65, wins: 0, podiums: 2, leadDrivers: "P. Gasly & E. Ocon", chassisName: "A524" },
];
import { quizQuestions, type QuizQuestion } from "./data/quiz";
export { quizQuestions, type QuizQuestion };



export function getCircuit(slug: string) {
  return circuits.find((circuit) => circuit.slug === slug);
}

export function getStory(slug: string) {
  return stories.find((story) => story.slug === slug);
}

export function getDriver(id: string) {
  return drivers2026.find((d) => d.id === id) || drivers2024.find((d) => d.id === id);
}

export function getDriversBySeason(season: "2026" | "2024" = "2026"): Driver[] {
  return season === "2024" ? drivers2024 : drivers2026;
}

export function getTeamsBySeason(season: "2026" | "2024" = "2026"): Team[] {
  return season === "2024" ? teams2024 : teams2026;
}

export const calendar2026SourceUrl = "https://www.formula1.com/en/racing/2026";

export type CalendarRace = {
  round: number;
  date: string;
  circuit: string;
  country: string;
  city: string;
  slug: string;
  note?: string;
};

export const calendar2026: CalendarRace[] = [
  { round: 1, date: "MAR 20 - 22", circuit: "Albert Park Circuit", country: "Australia", city: "Melbourne", slug: "albert-park" },
  { round: 2, date: "APR 03 - 05", circuit: "Shanghai International Circuit", country: "China", city: "Shanghai", slug: "shanghai" },
  { round: 3, date: "APR 10 - 12", circuit: "Suzuka International Racing Course", country: "Japan", city: "Suzuka", slug: "suzuka" },
  { round: 4, date: "MAY 01 - 03", circuit: "Miami International Autodrome", country: "United States", city: "Miami", slug: "miami", note: "SPRINT WEEKEND" },
  { round: 5, date: "MAY 15 - 17", circuit: "Circuit de Monaco", country: "Monaco", city: "Monte Carlo", slug: "monaco" },
  { round: 6, date: "MAY 29 - 31", circuit: "Circuit de Barcelona-Catalunya", country: "Spain", city: "Barcelona", slug: "barcelona" },
  { round: 7, date: "JUN 12 - 14", circuit: "Circuit Gilles-Villeneuve", country: "Canada", city: "Montreal", slug: "montreal" },
  { round: 8, date: "JUN 26 - 28", circuit: "Red Bull Ring", country: "Austria", city: "Spielberg", slug: "spielberg", note: "SPRINT WEEKEND" },
  { round: 9, date: "JUL 03 - 05", circuit: "Silverstone Circuit", country: "Great Britain", city: "Silverstone", slug: "silverstone" },
  { round: 10, date: "JUL 24 - 26", circuit: "Circuit de Spa-Francorchamps", country: "Belgium", city: "Spa", slug: "spa", note: "SPRINT WEEKEND" },
  { round: 11, date: "JUL 31 - AUG 02", circuit: "Hungaroring", country: "Hungary", city: "Budapest", slug: "hungaroring" },
  { round: 12, date: "AUG 21 - 23", circuit: "Circuit Zandvoort", country: "Netherlands", city: "Zandvoort", slug: "zandvoort", note: "ACTIVE ROUND" },
  { round: 13, date: "SEP 04 - 06", circuit: "Autodromo Nazionale Monza", country: "Italy", city: "Monza", slug: "monza" },
  { round: 14, date: "SEP 18 - 20", circuit: "MADRING (Circuito de Madrid)", country: "Spain", city: "Madrid", slug: "madrid", note: "INAUGURAL ROUND" },
  { round: 15, date: "SEP 25 - 27", circuit: "Baku City Circuit", country: "Azerbaijan", city: "Baku", slug: "baku" },
  { round: 16, date: "OCT 09 - 11", circuit: "Sepang International Circuit", country: "Malaysia", city: "Sepang", slug: "sepang" },
  { round: 17, date: "OCT 23 - 25", circuit: "Marina Bay Street Circuit", country: "Singapore", city: "Singapore", slug: "marina-bay" },
  { round: 18, date: "OCT 30 - NOV 01", circuit: "Circuit of the Americas", country: "United States", city: "Austin", slug: "austin", note: "SPRINT WEEKEND" },
  { round: 19, date: "NOV 06 - 08", circuit: "Autódromo Hermanos Rodríguez", country: "Mexico", city: "Mexico City", slug: "mexico-city" },
  { round: 20, date: "NOV 13 - 15", circuit: "Autódromo José Carlos Pace", country: "Brazil", city: "São Paulo", slug: "interlagos", note: "SPRINT WEEKEND" },
  { round: 21, date: "NOV 20 - 22", circuit: "Las Vegas Strip Circuit", country: "United States", city: "Las Vegas", slug: "las-vegas" },
  { round: 22, date: "NOV 27 - 29", circuit: "Lusail International Circuit", country: "Qatar", city: "Lusail", slug: "lusail", note: "SPRINT WEEKEND" },
  { round: 23, date: "DEC 04 - 06", circuit: "Yas Marina Circuit", country: "United Arab Emirates", city: "Abu Dhabi", slug: "yas-marina" },
];
